### ISSUE TITLE
Tokio no reactor running error 

### ISSUE THREAD

**Issue by shinglyu** [evcxr/evcxr#245]
I'm running the AWS Rust SDK in a notebook. 

I have the following cells:
Cell 1:
```yaml
:dep aws-config = "0.47.0"
:dep aws-sdk-sagemaker = "0.17.0"
:dep aws-sdk-sagemakerruntime = "0.17.0"
:dep tokio = { version = "1", features = ["full"]}
:dep aws-smithy-types-convert = { version = "0.47.0", features = ["convert-chrono"] }
```
Cell 2:
```rust
let config = aws_config::load_from_env().await;
```

If I try to use the `config` variable in subsequent cells, for example:
```rust
let client = aws_sdk_sagemaker::Client::new(&config);
let job_details = client.list_training_jobs().send().await?;
```
I got the following error:
```
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/context.rs:55:26
```

Not sure if this is related to how evcxr reuses the Tokio runtime? The Rust SDK also uses Tokio. 

I tried a workaround by repeating the following line in every cell that needs it:
```
let config = aws_config::load_from_env().await;
```
But then the code only works for the first execution, the 2nd call fails with some kind of timeout which I still need to debug further.

**Comment by bjorn3** [comment]
If you don't start a tokio runtime yourself, there will be none running at all. `#[tokio::main]` would start one for you if you are using it, but it won't work with evcxr as evcxr doesn't use a main function at all, but loads your code as dylib. Instead you did have to use `let rt = tokio::runtime::Runtime::new();` and then when writing code that needs tokio use `rt.block_on(async { /* your code here */ })`. I'm also not quite sure how tokio would react to it's thread local and global state being duplicated due to being linked into each of the dylibs generated for cells.

**Comment by shinglyu** [comment]
@bjorn3 Thank you for your suggestion. I tried to create a runtime myself but got this:

```rust
let mut runtime = tokio::runtime::Runtime::new().unwrap();
runtime.block_on(async{ let config = aws_config::load_from_env().await;})
```

```
thread '<unnamed>' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/mod.rs:89:25
stack backtrace:
   0: std::panicking::begin_panic
   1: tokio::runtime::enter::enter
   2: tokio::runtime::thread_pool::ThreadPool::block_on
   3: tokio::runtime::Runtime::block_on
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: std::thread::local::LocalKey<T>::with
   6: tokio::park::thread::CachedParkThread::block_on
   7: tokio::runtime::thread_pool::ThreadPool::block_on
   8: tokio::runtime::Runtime::block_on
   9: run_user_code_5
  10: evcxr::runtime::Runtime::run_loop
  11: evcxr::runtime::runtime_hook
  12: evcxr_jupyter::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bjorn3** [comment]
Forgot that evcxr already wraps your code in a tokio runtime if you use async, so using `tokio::runtime::Runtime::new()` yourself shouldn't be necessary. Not sure why the original panic happened then. You could try restarting evcxr and then running the original code you had or try restarting and then run the code you have right now with explicit tokio runtime. Restarting should clear out the state indicating if a tokio runtime should be added automatically or not.

**Comment by davidlattimore** [comment]
One possible way to debug this would be to run `:last_compile_dir` (poorly named, since it no longer changes), then run your code that produces an error and look at the code that was generated in the temporary directory. You can then see what edits need to be made to it in order to get it to work. If evcxr needs to generate different code in order to work with / without aws, then we'd have to figure out how to achieve that.

**Comment by davidlattimore** [comment]
One possibility that just occurred is perhaps evcxr is trying to use a different version of tokio than what aws expects. If that's the case, then explicitly pulling in tokio using the `:dep` command before you make any use of `.await`, should, I think, allow you control over which version gets used - at least I think it works that way for optional features, so it probably works that way for version as well.

**Comment by zhaofengli** [comment]
This is due to `CONTEXT` in tokio being a thread-local variable, and each loaded module has a separate instance separated with `pthread_key_create`.

More discussion: https://github.com/tokio-rs/tokio/discussions/5299

**Comment by bjorn3** [comment]
In that case the new dependency dylib mode which I believe is now the default fixes this.

**Comment by davidlattimore** [comment]
Unfortunately I reverted the default in the latest release because it was causing problems for too many people. You can enable dynamic linking of dependencies by doing `:allow_static_linking 0`

**Comment by 0xAlcibiades** [comment]
Hitting this issue as well, and if I follow :allow_static_linking 0 get an issue with cc, relates to #156

**Comment by davidlattimore** [comment]
@0xAlcibiades , if you're getting a link error when you enable `:allow_static_linking 0`, could you file a new issue? The underlying bug for #156 was fixed in rustc, so we'll need fresh repro instructions.

**Comment by naftulikay** [comment]
I'm on Linux amd64 kernel 6.8.0, `evcxr` version 0.18.0, Python 3.13.2, latest Jupyter. 

The behavior I'm seeing is that the first time I run a cell, Tokio/async stuff works perfectly fine, but running that same cell again has my tasks panic.

Cell contents:

```text
:dep jiff = "0.1"
:dep rand = "0.9"
:dep tokio = { version = "1", features = ["full"] }

use std::sync::Arc;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::time::Duration;

use jiff::Timestamp;
use rand::Rng;
use tokio::sync::Semaphore;

let semaphore = Arc::new(Semaphore::new(1));
let mut jobs = Vec::new();

const TASK_COUNT: usize = 10;

let in_flight = Arc::new(AtomicUsize::new(0));

for task_id in 0..TASK_COUNT {
    let in_flight = in_flight.clone();
    let semaphore = semaphore.clone();
    let job = tokio::spawn(async move {
        let _permit = semaphore.acquire().await.unwrap();
        in_flight.fetch_add(1, Ordering::AcqRel);

        let sleep_time = Duration::from_millis(rand::rng().random_range(10..=500u64));
        let rt_task_id = tokio::task::id();

        eprintln!(
            "{} [task_index={task_id} task_id={rt_task_id} in_flight={}] Sleeping for {sleep_time:?}", 
            Timestamp::now().to_string(),
            in_flight.load(Ordering::Acquire),
        );

        tokio::time::sleep(sleep_time).await;

        eprintln!(
            "{} [task_index={task_id} task_id={rt_task_id} in_flight={}] Done, dropping permit", 
            Timestamp::now().to_string(), 
            in_flight.load(Ordering::Acquire),
        );

        in_flight.fetch_sub(1, Ordering::AcqRel);
        drop(_permit);
    });

    jobs.push(job);
}

for job in jobs {
    let _resp = job.await.unwrap();
}
```

It seems that `tokio::time::sleep` is what causes the panic, here is the stacktrace:

```text
thread 'tokio-runtime-worker' panicked at src/lib.rs:134:9:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/core/src/panicking.rs:76:14
   2: tokio::runtime::scheduler::Handle::current::panic_cold_display
   3: tokio::runtime::scheduler::Handle::current
   4: tokio::time::sleep::sleep
   5: ctx::run_user_code_2::{{closure}}::{{closure}}::{{closure}}
   6: tokio::runtime::task::core::Core<T,S>::poll
   7: tokio::runtime::task::harness::Harness<T,S>::poll
   8: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run
  10: tokio::runtime::context::scoped::Scoped<T>::set
  11: tokio::runtime::context::runtime::enter_runtime
  12: tokio::runtime::scheduler::multi_thread::worker::run
  13: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  14: tokio::runtime::task::core::Core<T,S>::poll
  15: tokio::runtime::task::harness::Harness<T,S>::poll
  16: tokio::runtime::blocking::pool::Inner::run
```

I don't need the cell to maintain state across runs. Is there a way to have it run without maintaining state, if that's what's causing the problem? I imagine that trying to "persist" the Tokio runtime across cell runs is probably causing it.

**Comment by davidlattimore** [comment]
Does it work if you set `:allow_static_linking 0`?


> I don't need the cell to maintain state across runs. Is there a way to have it run without maintaining state, if that's what's causing the problem? I imagine that trying to "persist" the Tokio runtime across cell runs is probably causing it.

I think it'd be reasonable to have an option to turn off persisting of state and just restart the child process with each command. There isn't currently a setting for that, but I think you could make that happen by just putting `:restart` as the first line of your cell.

**Comment by naftulikay** [comment]
@davidlattimore Yes it works! Thanks!

**Comment by jsalort** [comment]
> This is due to `CONTEXT` in tokio being a thread-local variable, and each loaded module has a separate instance separated with `pthread_key_create`.
> 
> More discussion: [tokio-rs/tokio#5299](https://github.com/tokio-rs/tokio/discussions/5299)

I am running into the same problem, and for some reason `:allow_static_linking 0` does not work for me (I get `[E0433] Error: failed to resolve: use of unresolved module or unlinked crate`). I was wondering: is it possible to configure the tokio runtime in evcxr to be mono-threaded? In that case, shouldn't this remove the thread-local problem?

**Comment by bjorn3** [comment]
No, this has nothing to do with threads. Rather it caused by the fact that every cell gets an entirely separate copy of tokio for `:allow_static_linking 1` as is the default. This duplicates all global state of tokio. Both statics and thread-locals.
