### ISSUE TITLE
Jupyter Notebook v6.5.4 no longer works with the `rust` kernel

### ISSUE THREAD

**Issue by SichangHe** [evcxr/evcxr#301]
I just updated Jupyter Notebook to v6.5.4 and `evcxr_jupyter` no longer works.

Reproduce:

1. Launch Jupyter Notebook from the command-line.
2. Click on the top-right `New` button on its web interface.
3. Select `Rust` as the kernel.

It displays "500 Internal Error" on its web interface.

<details>
<summary>Full notebook log.</summary>

```sh
$ jupyter notebook

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|

Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 08:45:11.417 NotebookApp] Serving notebooks from local directory: /Users/sichanghe/AFileFolder/irrd_parse_policy
[I 08:45:11.417 NotebookApp] Jupyter Notebook 6.5.4 is running at:
[I 08:45:11.417 NotebookApp] http://localhost:8888/?token=ba7915eb6b18e915f44cd1b9880b823b9d90ec034c676799
[I 08:45:11.417 NotebookApp]  or http://127.0.0.1:8888/?token=ba7915eb6b18e915f44cd1b9880b823b9d90ec034c676799
[I 08:45:11.417 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:45:11.419 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///Users/sichanghe/Library/Jupyter/runtime/nbserver-56723-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=ba7915eb6b18e915f44cd1b9880b823b9d90ec034c676799
     or http://127.0.0.1:8888/?token=ba7915eb6b18e915f44cd1b9880b823b9d90ec034c676799
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 08:45:23.756 NotebookApp] Creating new notebook in
[E 08:45:23.915 NotebookApp] Uncaught exception GET /notebooks/Untitled.ipynb?kernel_name=rust (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Untitled.ipynb?kernel_name=rust', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/homebrew/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/tornado/gen.py", line 786, in run
        yielded = self.gen.send(value)
                  ^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/notebook/notebook/handlers.py", line 94, in get
        self.write(self.render_template('notebook.html',
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/notebook/base/handlers.py", line 515, in render_template
        return template.render(**ns)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
        self.environment.handle_exception()
      File "/opt/homebrew/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/opt/homebrew/lib/python3.11/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/opt/homebrew/lib/python3.11/site-packages/notebook/templates/page.html", line 187, in top-level template code
        {% block header %}
      File "/opt/homebrew/lib/python3.11/site-packages/notebook/templates/notebook.html", line 115, in block 'header'
        {% for exporter in get_frontend_exporters() %}
        ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/opt/homebrew/lib/python3.11/site-packages/nbconvert/__init__.py", line 7, in <module>
        from .exporters import *
      File "/opt/homebrew/lib/python3.11/site-packages/nbconvert/exporters/__init__.py", line 4, in <module>
        from .html import HTMLExporter
      File "/opt/homebrew/lib/python3.11/site-packages/nbconvert/exporters/html.py", line 28, in <module>
        from nbconvert.filters.markdown_mistune import IPythonRenderer, MarkdownWithMath
      File "/opt/homebrew/lib/python3.11/site-packages/nbconvert/filters/markdown_mistune.py", line 17, in <module>
        from mistune import PLUGINS, BlockParser, HTMLRenderer, InlineParser, Markdown  # type:ignore
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ImportError: cannot import name 'PLUGINS' from 'mistune' (/opt/homebrew/lib/python3.11/site-packages/mistune/__init__.py)
[E 08:45:23.921 NotebookApp] {
      "Host": "localhost:8888",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
      "Referer": "http://localhost:8888/tree",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
    }
[E 08:45:23.921 NotebookApp] 500 GET /notebooks/Untitled.ipynb?kernel_name=rust (::1) 114.730000ms referer=http://localhost:8888/tree
```

</details>

Jupyter Notebook version:

```sh
$ jupyter notebook --version
6.5.4
```

It seems that Jupyter Notebook is changing their API and breaking user space. If you don't want to work with them, I suggest adding a maximum supported notebook version to the documentation.

**Comment by SichangHe** [comment]
After rolling Jupyter Notebook back one patch version, it worked again.

```sh
pip3 install notebook==6.5.3 --force-reinstall
```
